start "" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "https://mail.google.com/mail/u/0/#inbox" "https://keep.google.com/#home" "https://www.google.com/calendar/render?tab=mc#main_7" "https://docs.google.com/spreadsheets/d/16rpGdHdR-XPHba5kbNoWtSOQIZjXiJEr_FOIbl9HhLU/edit#gid=0" "https://www.clicktime.com/?home=true"
start "" "C:\Program Files (x86)\Vim\vim74\gvim.exe"
start "" "C:\Program Files\HexChat\hexchat.exe"
start "" "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe" --comment "NetworkGuardianAMD64" --startvm "c9598931-04fd-4e61-abbc-50aec8a88cbb"
start "" "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe" --comment "kubuntu" --startvm "ff7c4bde-73c8-431f-b71a-d2e77d5da47d"
start "" "C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
