start "" "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe" --comment "Guardain_EG" --startvm "267c96cb-674a-49c2-a94b-2645bf80f76c"
start "" "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe" --comment "kubuntu" --startvm "ff7c4bde-73c8-431f-b71a-d2e77d5da47d"
start "" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
start "" "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe"
start "" "C:\Program Files (x86)\Vim\vim74\gvim.exe"
start "" "C:\Program Files\HexChat\hexchat.exe"
start "" "C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
start "" "C:\Windows\System32\services.msc"
